name: sonic3air
base: core24
version: '24.02.02.0-stable'
platforms:
  amd64:
    build-on: [amd64]
    build-for: [amd64]
summary: Fan-made remaster of Sonic 3&K
description: |
  Dr. Eggman’s (AKA Dr. Robotnik’s) Death Egg was once again blasted by Sonic, crash-landing on the peak of a volcano on the Floating Island.

  Dr. Eggman is still at large, and Sonic can’t allow him to get his hands on the Master Emerald and repair the Death Egg. Sonic must also keep Knuckles off his back but Knuckles has problems too. As guardian of the Floating Island and all the Emeralds, Knuckles must do his part to keep the island safe. While they’re going the rounds with each other, who will stop Dr. Eggman?

  To play Sonic 3 - Angel Island Revisited, you need Sonic 3 & Knuckles from the SEGA Mega Drive & Genesis Classics collection installed on Steam.
grade: stable
confinement: strict
icon: sonic3air.png

apps:
  sonic3air:
    command: sonic3air-launcher.sh
    desktop: org.sonic3air.Sonic3AIR.desktop
    common-id: org.sonic3air.Sonic3AIR
    environment:
      HOME: $SNAP_REAL_HOME
    extensions: [gnome]
    plugs:
      - unity7
      - audio-playback
      - network
      - network-bind
      - screen-inhibit-control
      - home
      - removable-media
      - mount-observe
      - joystick
      - bluez

plugs:
  shared-memory:
    private: true

parts:
  sonic3air-app:
    plugin: dump
    source: https://github.com/Eukaryot/sonic3air/releases/download/v$SNAPCRAFT_PROJECT_VERSION/sonic3air_game.tar.gz
    override-build: |
      craftctl default
      chmod 777 $CRAFT_PART_INSTALL/data/*
    prime:
      - data
      - config.json
      - libdiscord_game_sdk.so
      - sonic3air_linux

  sonic3air-launcher:
    after: [sonic3air-app]
    plugin: dump
    source: ./gui
    prime:
      - org.sonic3air.Sonic3AIR.desktop
      - sonic3air-launcher.sh

  zenity:
    after: [sonic3air-launcher]
    plugin: nil
    stage-packages: [zenity]
    prime: [usr/bin/zenity]
