name: sonic3air
base: core24
version: '24.02.02.0-stable'
platforms:
  amd64:
    build-on: [amd64]
    build-for: [amd64]
summary: Fan-made remaster of Sonic 3&K
description: |
  Dr. Eggman’s (AKA Dr. Robotnik’s) Death Egg was once again blasted by Sonic, crash-landing on the peak of a volcano on the Floating Island.

  Dr. Eggman is still at large, and Sonic can’t allow him to get his hands on the Master Emerald and repair the Death Egg. Sonic must also keep Knuckles off his back but Knuckles has problems too. As guardian of the Floating Island and all the Emeralds, Knuckles must do his part to keep the island safe. While they’re going the rounds with each other, who will stop Dr. Eggman?

  To play Sonic 3 - Angel Island Revisited, you need Sonic 3 & Knuckles from the SEGA Mega Drive & Genesis Classics collection installed on Steam.
grade: stable
confinement: strict

apps:
  sonic3air:
    command: usr/bin/sonic3air
    desktop: usr/applications/sonic3air.desktop
    common-id: org.sonic3air.Sonic3AIR
    extensions: [kde-neon-6]
    environment:
      QT_QPA_PLATFORMTHEME: kde
    plugs:
      - unity7
      - screen-inhibit-control
      - audio-playback
      - network
      - network-bind
      - home
      - removable-media
      - mount-observe
      - joystick
      - bluez

package-repositories:
  - type: apt
    url: http://origin.archive.neon.kde.org/user
    suites: [noble]
    components: [main]
    architectures: [amd64]
    key-id: 444DABCF3667D0283F894EDDE6D4736255751E5D

parts:
  sonic3air:
    plugin: dump
    source: https://github.com/Eukaryot/sonic3air/releases/download/v$SNAPCRAFT_PROJECT_VERSION/sonic3air_game.tar.gz
    override-build: |
      mkdir -p $CRAFT_PART_INSTALL/usr/bin/
      mkdir -p $CRAFT_PART_INSTALL/usr/lib/
      mv -f sonic3air_linux $CRAFT_PART_INSTALL/usr/bin/
      mv -f libdiscord_game_sdk.so $CRAFT_PART_INSTALL/usr/lib/
      mv -f data $CRAFT_PART_INSTALL/usr/bin/
      mv -f config.json $CRAFT_PART_INSTALL/usr/bin/
      chmod -R 777 $CRAFT_PART_INSTALL/usr/bin/data
    prime:
      - usr/bin/sonic3air_linux
      - usr/lib/libdiscord_game_sdk.so
      - usr/bin/data/
      - usr/bin/config.json

  sonic3air-launcher:
    after: [sonic3air]
    plugin: nil
    source: ./launcher
    override-build: |
      mkdir -p $CRAFT_PART_INSTALL/usr/bin/
      mkdir -p $CRAFT_PART_INSTALL/usr/applications
      mkdir -p $CRAFT_PART_INSTALL/usr/share/icons/hicolor/scalable/apps
      mv -f sonic3air-launcher.sh $CRAFT_PART_INSTALL/usr/bin/sonic3air
      mv -f sonic3air.desktop $CRAFT_PART_INSTALL/usr/applications/
      mv -f sonic3air.png $CRAFT_PART_INSTALL/usr/share/icons/hicolor/scalable/apps/
      chmod 777 $CRAFT_PART_INSTALL/usr/bin/sonic3air
    prime:
      - usr/bin/sonic3air
      - usr/applications/sonic3air.desktop
      - usr/share/icons/hicolor/scalable/apps/sonic3air.png

  qarma:
    after: [sonic3air-launcher]
    plugin: nil
    build-packages: [qmake6]
    source: https://github.com/luebking/qarma.git
    source-tag: v1.0.0
    override-build: |
      qmake6 PREFIX=$CRAFT_PART_INSTALL/
      make
      make install
